name: metallb
chart: metallb
repoURL: https://metallb.github.io/metallb
version: 0.14.3
namespace: metallb-system
environments:
  - dev
  - prd
ignoreDifferences:
  # Ignore dynamic loadBalancer status managed by metallb
  - group: ""
    kind: Service
    jsonPointers:
      - /status/loadBalancer/ingress
