apiVersion: v1
kind: Service
metadata:
  name: ids
  namespace: ids-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.246
  selector:
    app: ids
  ports:
    - name: http
      port: 3000
      targetPort: 3000
