name: ingress-nginx
chart: ingress-nginx
repoURL: https://kubernetes.github.io/ingress-nginx
version: 4.9.1
namespace: ingress-nginx
environments:
  - dev
  - prd
ignoreDifferences:
  # Ignore HPA API version differences (v1 vs v2)
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jqPathExpressions:
      - .spec.metrics
      - .status
