apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/nic5694-homelab/gitops-operators.git
              revision: HEAD
              files:
                - path: "apps/**/config.yaml"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-{{.nameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: operators
      sources:
        - chart: '{{.chart}}'
          repoURL: '{{.repoURL}}'
          targetRevision: '{{.version}}'
          helm:
            releaseName: '{{.name}}'
            valueFiles:
              - $values/apps/{{.name}}/values.yaml
              - $values/apps/{{.name}}/clusters/{{.nameNormalized}}/values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/nic5694-homelab/gitops-operators.git
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
  templatePatch: |
    {{ $envMatch := false }}
    {{ range .environments }}
      {{ if eq . $.nameNormalized }}
        {{ $envMatch = true }}
      {{ end }}
    {{ end }}
    {{ if not $envMatch }}
    metadata:
      name: ''
    {{ end }}
    {{ if gt (len .ignoreDifferences) 0 }}
    spec:
      ignoreDifferences:
      {{ range .ignoreDifferences }}
        - group: '{{ .group }}'
          kind: '{{ .kind }}'
          {{ if .jsonPointers }}
          jsonPointers:
          {{ range .jsonPointers }}
            - '{{ . }}'
          {{ end }}
          {{ end }}
          {{ if .jqPathExpressions }}
          jqPathExpressions:
          {{ range .jqPathExpressions }}
            - '{{ . }}'
          {{ end }}
          {{ end }}
      {{ end }}
    {{ end }}
