apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/nic5694-homelab/gitops-operators.git
              revision: HEAD
              files:
                - path: "apps/**/config.yaml"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-{{.nameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: operators
      sources:
        - chart: '{{.chart}}'
          repoURL: '{{.repoURL}}'
          targetRevision: '{{.version}}'
          helm:
            releaseName: '{{.name}}'
            valueFiles:
              - $values/apps/{{.name}}/values.yaml
              - $values/apps/{{.name}}/clusters/{{.nameNormalized}}/values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/nic5694-homelab/gitops-operators.git
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
  templatePatch: |
    {{ $ignoreDiffs := index . "ignoreDifferences" }}
    {{ if and $ignoreDiffs (gt (len $ignoreDiffs) 0) }}
    spec:
      ignoreDifferences:
      {{ range $ignoreDiffs }}
        - group: '{{ index . "group" }}'
          kind: '{{ index . "kind" }}'
          {{ $jsonPointers := index . "jsonPointers" }}
          {{ if $jsonPointers }}
          jsonPointers:
          {{ range $jsonPointers }}
            - '{{ . }}'
          {{ end }}
          {{ end }}
          {{ $jqExpressions := index . "jqPathExpressions" }}
          {{ if $jqExpressions }}
          jqPathExpressions:
          {{ range $jqExpressions }}
            - '{{ . }}'
          {{ end }}
          {{ end }}
      {{ end }}
    {{ end }}
